/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './resources/views/**/*.blade.php',
        './public/js/**/*.js',
    ],
    theme: {
        extend: {
            colors: {
                'on-secondary-container': '#5c647a',
                'primary-container': '#4f46e5',
                'surface-container-high': '#dce9ff',
                'on-primary': '#ffffff',
                'surface-container-lowest': '#ffffff',
                'inverse-primary': '#c3c0ff',
                'surface-dim': '#cbdbf5',
                'surface-container-low': '#eff4ff',
                'secondary-fixed': '#dae2fd',
                'inverse-on-surface': '#eaf1ff',
                'on-primary-fixed': '#0f0069',
                'on-error-container': '#93000a',
                'outline-variant': '#c7c4d8',
                'secondary': '#565e74',
                'primary-fixed-dim': '#c3c0ff',
                'on-primary-fixed-variant': '#3323cc',
                'primary-fixed': '#e2dfff',
                'background': '#f8f9ff',
                'surface': '#f8f9ff',
                'surface-variant': '#d3e4fe',
                'tertiary-fixed': '#e0e3e5',
                'secondary-fixed-dim': '#bec6e0',
                'error': '#ba1a1a',
                'on-secondary-fixed-variant': '#3f465c',
                'error-container': '#ffdad6',
                'on-background': '#0b1c30',
                'outline': '#777587',
                'on-surface-variant': '#464555',
                'surface-container': '#e5eeff',
                'on-tertiary-container': '#dadcde',
                'on-tertiary': '#ffffff',
                'tertiary': '#46494b',
                'on-error': '#ffffff',
                'on-tertiary-fixed-variant': '#444749',
                'surface-container-highest': '#d3e4fe',
                'tertiary-fixed-dim': '#c4c7c9',
                'on-surface': '#0b1c30',
                'on-tertiary-fixed': '#191c1e',
                'on-secondary-fixed': '#131b2e',
                'surface-tint': '#4d44e3',
                'on-primary-container': '#dad7ff',
                'secondary-container': '#dae2fd',
                'primary': '#3525cd',
                'inverse-surface': '#213145',
                'tertiary-container': '#5e6163',
                'surface-bright': '#f8f9ff',
                'on-secondary': '#ffffff',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                '2xl': '1.5rem',
                full: '9999px',
            },
            spacing: {
                'container-max': '1280px',
                'stack-md': '1rem',
                'margin-mobile': '1rem',
                'section-padding': '5rem',
                gutter: '1.5rem',
                'stack-lg': '2rem',
                'stack-sm': '0.5rem',
            },
            fontFamily: {
                sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
                'display-lg': ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
                'display-lg-mobile': ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
                'headline-xl': ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
                'headline-lg': ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
                'label-md': ['Inter', 'sans-serif'],
                'body-lg': ['Inter', 'sans-serif'],
                'body-md': ['Inter', 'sans-serif'],
            },
            fontSize: {
                'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
                'display-lg-mobile': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
                'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
                'headline-xl': ['36px', { lineHeight: '1.2', fontWeight: '700' }],
                'headline-lg': ['30px', { lineHeight: '1.3', fontWeight: '700' }],
                'display-lg': ['60px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
                'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
            },
        },
    },
    plugins: [],
}
